/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 05.11.2025 13:44:38

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 2704;
#else
constexpr int kTensorArenaSize = 1680;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,72 } };
const TfArray<1, float> quant0_scale = { 1, { 0.031372550874948502, } };
const TfArray<1, int> quant0_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 72, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 72, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 36, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data4[2] = { -1, 360, };
const TfArray<1, int> tensor_dimension4 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[5] = { -205, 548, -385, -277, -404, };
const TfArray<1, int> tensor_dimension5 = { 1, { 5 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00019142319797538221, } };
const TfArray<1, int> quant5_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[5*360] = { 
  72, 20, -92, 24, -102, -91, 57, -11, 12, 48, -21, -36, 24, 10, -2, -15, -27, -11, -12, -23, 6, -28, -29, -83, -62, -16, -16, -64, -28, -2, -3, -24, -67, 45, -15, -82, -8, -4, -25, -6, -33, -14, 55, -15, 46, 58, -31, -30, -30, -47, -37, -2, -38, -32, -46, 16, 4, -57, -13, -9, -11, 11, -53, 28, -10, -39, -19, 47, -15, -43, -57, -28, 65, -48, 20, 46, -49, -18, -29, -54, -35, 1, -32, -55, -48, 6, -20, -6, 26, -45, 17, -59, -40, 35, 17, 0, 36, 36, 2, -18, -29, -56, 42, -26, 2, 35, -14, -5, 5, -46, -37, 32, -1, -31, -27, 20, -47, 7, 31, -36, -10, 9, 16, 11, 4, 18, -5, 3, -14, -3, 8, -35, 31, -7, 51, 38, 23, 0, -1, -17, -1, 20, -20, 19, -52, -2, 0, -16, -1, -32, -20, 30, 16, 23, -12, -21, -25, 23, 23, 13, -5, -52, 21, -45, 50, 29, 8, -14, -23, 3, -19, 8, -25, 19, -17, -25, -38, 20, -18, -10, 5, 38, 39, 8, -7, 24, 6, 34, 19, -10, 6, -27, 18, 17, 35, 43, 24, 25, 17, 9, -21, -8, -3, 45, -39, -16, 22, 8, 16, -34, -9, 39, 23, 2, 31, 22, -17, 5, 11, -27, -5, -24, 3, -16, 18, 49, 21, -1, -8, 25, -13, -23, -7, 9, 1, -2, -21, -3, 14, 1, -15, 16, -10, -29, 3, 41, -42, -23, 29, -1, 12, -15, -55, 28, -22, -6, 34, 3, 32, -11, 19, -21, 35, -5, 5, -11, -16, 6, -20, -18, 11, 30, 10, -33, -49, 18, -22, 4, -10, 0, 49, 22, -31, -6, -40, -73, 11, 18, 29, 33, -2, -45, 1, 13, 12, -28, -8, 12, -16, -8, 21, 39, 9, -42, -70, 19, -15, -20, 38, 8, 41, -13, -31, 18, -57, -21, 41, 12, 8, 42, 4, -14, 6, 49, -19, -56, 17, 23, -39, 10, -37, 10, 58, -19, -58, 25, -40, -27, 7, 3, 25, 29, -63, 9, -110, -99, 59, 8, 31, 54, 28, -22, 11, 45, -4, -18, 15, 9, -19, -6, 
  32, 59, 55, 51, 46, 68, 55, 62, 58, 38, -23, 8, 30, 31, 28, 50, -8, 21, 31, 9, 18, 67, 35, 54, 17, 28, 18, 14, 20, 14, 18, 20, 40, 14, 54, 44, 76, 10, 20, 55, 33, 0, 34, -20, 12, 54, 14, -17, -7, 27, -3, 63, 53, 14, -24, 8, -3, 10, 3, 15, -1, 23, 48, 7, 41, -20, -6, 10, -16, 40, 5, 21, 41, 7, 9, 23, -23, 0, -14, 22, 4, -19, 16, -41, 12, -5, -20, -16, -9, 19, 12, 29, 49, 30, -33, -51, -41, -38, -14, -4, -10, 10, 35, 1, 18, 3, -23, -6, -23, -25, 33, -14, 30, -21, -12, 1, -12, -51, -33, 34, -1, 42, 12, 11, 2, -56, -78, -2, -9, -11, -5, -24, 43, -8, 29, 29, -3, -46, 3, 4, -4, -9, 43, -47, -5, -35, -4, -42, -8, 45, 32, 54, -18, -13, -15, -25, -63, -14, -15, 1, 8, -24, 31, -32, 19, -4, -36, -26, -1, -33, 5, -16, 48, -34, 12, -37, -25, -30, -37, 20, -4, 54, 26, 20, 3, -50, -50, -26, -30, 8, 12, -1, 28, 3, 8, 3, 14, -12, -36, 6, 1, -24, 45, -30, -19, 3, 16, -33, -13, 30, 17, 23, 23, 3, -24, -4, -56, -24, -29, 1, 25, -1, 31, 1, 16, -32, 5, -29, -36, -17, 25, -9, 36, -33, -14, -37, 10, -47, -35, 24, -18, 17, 44, -12, -1, -38, -57, -15, -9, -7, -8, -14, 15, 4, 23, 40, -21, -34, -14, -17, 31, -31, 12, -47, 6, -19, -11, -43, -46, -5, -4, 41, 7, 0, 46, -54, -38, -22, -14, -5, -15, 6, 20, -27, 50, 29, -8, 3, -15, -32, 20, -21, 26, -47, -11, -25, 3, -25, -31, -15, 24, 48, 33, -16, 3, -31, -16, -38, 5, -12, 16, -18, 7, 10, 8, 1, 11, 5, -3, 24, 12, 10, 9, -15, 30, 19, -16, 2, 14, 7, 31, 21, 46, -8, 36, -20, 13, -22, -11, 37, 27, 18, 4, 30, 20, 8, -12, 3, 2, 26, 15, -14, 45, 30, 43, 11, -15, -1, 4, -3, 
  -90, -44, -50, -36, -56, 4, -37, -32, 8, -23, 23, 45, 36, 41, -102, -75, 17, 5, 27, 25, -52, -85, -55, -2, 49, -1, 54, -7, 16, 8, -54, 17, -43, 14, -91, -19, -95, 1, 20, -35, -4, 50, 9, 37, -51, -43, 15, 47, 15, 1, -21, -120, -25, 11, 32, 34, 52, 10, 7, -4, -67, -16, -29, -15, -30, 54, -48, -10, 16, -74, -3, 35, 27, 16, -39, -37, -23, 11, 28, -14, -45, -60, -40, -3, 65, 53, 19, -7, 22, -35, -17, -17, -40, -10, -14, 11, -3, 4, 12, -18, -36, 26, 6, 45, 6, -6, -18, 34, 4, 15, -21, -51, -54, -5, 53, 30, 26, 3, 2, 8, -4, -28, -28, 9, -7, -14, 28, 10, -21, -38, -1, 25, 33, 15, -73, -48, -1, 13, 1, 14, -20, 21, -19, -4, 18, 36, 46, 12, 31, -16, 15, -17, -49, 5, -26, 22, 30, 7, -24, 17, 4, 19, -19, 16, -24, -59, -34, -10, -11, -3, 23, -24, -49, -6, -10, -14, 20, 23, -14, 2, -2, -61, -73, -28, -32, 16, 30, 9, -18, -10, -39, 5, -47, -7, -42, -65, -21, -14, -7, -27, 1, 40, -18, 18, 25, 14, 30, -11, 25, -8, 39, -64, -70, -19, 27, 21, 22, -15, -5, 29, 1, 11, -24, -3, -44, -31, -15, 26, -6, 8, -3, 24, -24, -18, -3, 11, 6, 4, -2, 25, 21, -40, -56, -17, 8, 5, 31, 16, 0, 37, -44, -12, -50, -4, -56, -59, -19, -14, -19, -25, -5, 26, -22, 20, -22, -25, 0, 6, 5, 6, 69, -77, -25, -35, 19, -3, 41, -7, 8, -6, -3, -30, -61, 1, -6, -29, 0, 0, 1, -11, 2, 39, 5, -5, -56, -19, -31, 23, 7, 30, 19, -53, -37, 5, 24, -4, 44, -9, -8, 9, 11, -9, -91, -28, -36, -1, -37, 2, -46, -6, 49, 47, -21, 4, -50, -25, -13, -8, -20, 33, 23, -51, -49, -35, 2, -36, 38, 6, -25, 28, 15, -46, -95, -52, -56, 9, -18, -14, -24, -17, 40, 12, -42, -19, -109, -82, -11, -7, -4, -6, 
  -6, -21, -26, -62, -34, -23, -76, -85, -69, -43, 4, -42, -75, -27, -20, -78, 28, -42, -58, -15, -6, 0, -35, 2, -84, -96, -48, 10, -70, -10, 0, -13, -25, -70, -50, -41, 28, -59, -10, 6, 3, -45, -115, -56, -41, -90, 20, -47, -54, 27, 50, 52, -47, 18, -89, -93, -17, 11, -9, 45, 70, -42, -43, -29, -10, -36, 62, -31, -7, 45, 20, 0, -127, -30, -62, -27, -36, -2, 0, 16, 26, 66, -22, 28, -77, -79, -20, 4, 36, 29, 34, -65, -37, -6, 16, 6, 37, 1, -4, 39, -15, 5, -112, -31, -44, -66, -40, 6, -40, 5, 26, 39, 19, 30, -90, -27, -32, 32, 33, 34, 55, -44, -24, -14, 17, -5, 65, -4, -22, 47, -25, 7, -103, -1, -77, -51, -31, -2, -13, 9, 21, 22, -20, 4, 29, -7, 6, 4, -4, -14, 40, -42, -50, 1, 37, 12, 10, -1, 19, 24, -14, 3, -16, 15, -45, -39, -5, -11, -10, 4, 3, -1, 10, 7, 8, 10, 2, 20, 0, -8, 27, -57, -31, 19, 20, 4, 35, 34, 4, 4, -20, 40, -19, 13, 0, -43, -15, 33, -17, -5, 7, -10, -31, -17, 21, 8, 9, -4, 8, -18, -16, -18, -14, 12, 9, 2, 2, 21, 16, -5, -45, 10, 17, 8, -67, -35, -25, 6, 14, -18, 5, 15, -15, -15, 6, 7, 15, 5, 2, -4, -13, -34, -11, -15, -6, 22, -20, -5, -1, 13, -5, 26, 42, 6, 1, 4, -53, 6, 25, 0, -1, 11, -23, 15, 28, 9, 25, -12, -2, 11, -19, -12, -59, -27, -1, -16, -5, 24, 3, -16, -35, 47, 10, 10, -68, -37, -19, 23, 33, 12, -24, -50, -51, 0, 53, 19, 35, -9, -13, -23, -36, -13, -34, 18, 4, 3, -29, 9, -13, -25, 2, 52, 1, 43, -14, -6, -9, -6, 11, -25, -22, -58, -29, -29, 47, 37, 9, 18, 19, -22, -58, 7, -29, -32, -38, 49, -40, 19, 10, -36, -8, 56, 9, 41, -45, -38, -14, 17, 29, -13, -37, -99, -14, 7, 49, 25, 21, -16, 4, -32, 
  -50, -62, -5, -56, -20, 28, -50, -73, -34, -32, 11, 1, -89, -20, -103, -58, -12, -14, -28, 6, 7, -22, -50, 33, -43, -53, -1, -2, -17, -38, -39, -13, -5, -68, -54, 29, -17, -48, 17, -8, 6, -26, -75, -1, -106, -77, 38, -29, 0, 18, -22, -51, -45, 45, -12, -48, -15, -7, -12, 3, -51, 24, 40, -92, -72, 1, -11, -13, 22, 9, 20, -3, -97, -21, -103, -80, 55, -2, -6, 10, 22, -61, -13, 42, -42, -71, -7, 50, 8, 0, -45, 12, 50, -87, -56, 4, -12, -2, 5, 31, 47, -29, -124, 12, -94, -28, 72, 14, 34, 42, -12, -24, -60, 39, 7, -7, 16, 51, 1, 22, -51, 24, 10, -33, -57, 18, -4, -31, 36, 7, 30, -5, -94, 9, -57, -20, 42, 5, -9, 43, 0, -11, -57, 25, 0, -12, -6, 27, -7, 3, -17, 33, 1, -7, -7, 18, -27, -9, 4, -18, 31, -42, -37, -30, -17, 11, 31, -28, 21, -8, -33, -30, -45, 29, -44, -35, -29, 7, -17, -41, -61, 10, 23, -43, -47, 15, -34, 8, -16, -24, 5, -19, 6, -18, -12, 23, 6, 3, -24, 8, -22, -14, -41, 3, -51, -7, -56, 1, 3, -13, -34, -4, 33, 17, -40, -19, -6, -12, 13, 7, 5, 0, 17, 4, 3, 33, 2, 13, 7, 10, -44, -21, -47, -9, -77, -27, -29, 25, -17, -12, -41, -6, 18, 17, -41, 27, 28, 6, 40, -10, 22, -10, -5, 17, -1, 58, 20, -7, -9, 14, -1, 1, -36, 25, -59, -28, 5, -9, -1, -11, -35, 8, -23, 6, -45, 5, 0, 37, 45, 10, 5, -24, 38, -5, 46, 39, 44, 31, -9, -1, -26, 0, -34, -13, -35, 37, -10, -10, -3, -47, -31, -6, -36, 35, 17, 2, 24, 35, 45, -11, -28, -61, 42, -3, 21, 10, 4, -22, 7, -33, -55, -4, -35, -28, -27, 35, -34, -42, 6, -36, -6, -14, -62, 31, 11, -24, 22, 23, 14, -6, -54, -50, 82, -23, 52, 45, -62, -20, -20, -33, -68, -1, -44, -52, -43, 43, -36, -79, 16, -50, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 5,360 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0050124949775636196, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[10] = { 892, 1309, 1883, 368, 2015, 1515, -543, -950, -638, 755, };
const TfArray<1, int> tensor_dimension7 = { 1, { 10 } };
const TfArray<1, float> quant7_scale = { 1, { 0.00017620348080527037, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[10*1*1*8] = { 
  /* [0][0][][] */ 57,-103,-42,-2,84,37,107,-64, 
  /* [1][0][][] */ -32,-75,86,79,60,-5,-25,-81, 
  /* [2][0][][] */ -17,-58,5,112,-12,-24,-31,16, 
  /* [3][0][][] */ 91,27,101,38,-76,103,3,-79, 
  /* [4][0][][] */ -6,75,-81,15,-41,84,-10,49, 
  /* [5][0][][] */ -45,92,-47,85,11,-57,-21,89, 
  /* [6][0][][] */ 127,39,-67,-42,89,112,46,13, 
  /* [7][0][][] */ 33,88,68,69,-14,98,98,-79, 
  /* [8][0][][] */ 59,46,62,48,84,43,-83,-19, 
  /* [9][0][][] */ 57,-77,-6,2,80,99,6,25, 
};
const TfArray<4, int> tensor_dimension8 = { 4, { 10,1,1,8 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0071233636699616909, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[8] = { 161, -590, -487, 1792, 641, 932, 263, 419, };
const TfArray<1, int> tensor_dimension9 = { 1, { 8 } };
const TfArray<1, float> quant9_scale = { 1, { 0.00019937723118346184, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[8*1*3*1] = { 
  /* [0][0][][] */ -36, 105, 3, 
  /* [1][0][][] */ -108, -108, 19, 
  /* [2][0][][] */ 106, 70, -106, 
  /* [3][0][][] */ -104, 1, 30, 
  /* [4][0][][] */ 113, -21, 1, 
  /* [5][0][][] */ -59, 78, -11, 
  /* [6][0][][] */ 17, 127, 18, 
  /* [7][0][][] */ 60, -65, 39, 
};
const TfArray<4, int> tensor_dimension10 = { 4, { 8,1,3,1 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0063551487401127815, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const TfArray<4, int> tensor_dimension11 = { 4, { 1,1,72,1 } };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,72,8 } };
const TfArray<1, float> quant12_scale = { 1, { 0.024735994637012482, } };
const TfArray<1, int> quant12_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,72,1,8 } };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,36,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,1,36,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,36,10 } };
const TfArray<1, float> quant16_scale = { 1, { 0.038189206272363663, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfArray<2, int> tensor_dimension17 = { 2, { 1,360 } };
const TfArray<2, int> tensor_dimension18 = { 2, { 1,5 } };
const TfArray<1, float> quant18_scale = { 1, { 0.18566574156284332, } };
const TfArray<1, int> quant18_zero = { 1, { 30 } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&quant18_zero, 0 };
const TfArray<1, float> quant19_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 11,10,9 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 12,2 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 13 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 14,3 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 15,8,7 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 16,4 } };
const TfArray<1, int> outputs6 = { 1, { 17 } };
const TfLiteFullyConnectedParams opdata7 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs7 = { 3, { 17,6,5 } };
const TfArray<1, int> outputs7 = { 1, { 18 } };
const TfLiteSoftmaxParams opdata8 = { 1 };
const TfArray<1, int> inputs8 = { 1, { 18 } };
const TfArray<1, int> outputs8 = { 1, { 19 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension12, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension14, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension16, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension17, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension18, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 20, };
const size_t tflNodes_subgraph_index[] = {0, 9, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  19, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_792000_36_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 20;
  for (size_t i = 0; i < 20; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_invoke() {
  for (size_t i = 0; i < 9; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
