/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 08.04.2026 23:11:00

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 2704;
#else
constexpr int kTensorArenaSize = 1680;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,72 } };
const TfArray<1, float> quant0_scale = { 1, { 0.033744722604751587, } };
const TfArray<1, int> quant0_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 72, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 72, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 36, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data4[2] = { -1, 360, };
const TfArray<1, int> tensor_dimension4 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[6] = { -213, 478, -292, 6, -329, -290, };
const TfArray<1, int> tensor_dimension5 = { 1, { 6 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00038378924364224076, } };
const TfArray<1, int> quant5_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[6*360] = { 
  19, 27, -9, 14, -43, 14, 14, 15, -8, 11, -33, -34, -13, -18, 31, 39, -7, -5, 1, -26, -6, -5, 12, -3, -22, -11, -8, 1, -9, 24, 2, -33, 5, 0, -14, 22, -23, 3, -25, 15, -7, -30, 15, -15, 45, 15, 1, 23, -24, 9, -8, -24, 6, -21, -32, -12, -2, -6, -15, -11, -1, -2, -11, 29, -11, -3, -3, 6, 9, 4, -4, -49, -3, -37, 86, 35, 9, 15, 1, 13, 16, -21, -2, -19, -46, -14, 6, 8, -17, 9, 1, -19, 1, 20, -21, 23, -9, 2, 2, -2, -10, -31, 15, -12, 68, 17, 16, -8, 7, -3, -5, 6, -16, -15, -27, -6, 3, -8, -10, -34, -23, -19, 15, 8, -24, 2, -5, 3, -1, -4, -14, -27, -15, -15, 78, 20, -3, 10, -8, 7, -11, -17, 6, -28, -51, -21, -18, -5, -13, -23, -10, 5, -13, 23, -15, 23, -20, -2, 3, -7, 25, -17, 9, -27, 39, 10, 21, 5, -22, -2, -12, 5, 12, -13, -7, 8, -18, -12, 1, -17, -8, 1, -2, 13, -28, 8, 3, 5, 2, -4, 0, -21, -11, -15, 20, 3, 12, 5, -4, 9, 15, -25, 1, -15, -26, -21, 6, 7, 5, -20, -15, 17, -16, 32, -12, 29, -15, -3, 17, 10, 19, -31, 2, -18, 18, 15, 20, 18, -14, 7, -6, -13, 15, 4, -14, 0, -18, 15, -1, -11, 5, -1, -13, 8, -30, 14, -21, 0, -6, -4, 24, 1, -11, 3, 30, 17, -4, 15, 0, 6, 2, -7, 9, 6, -16, -13, 3, 22, -23, -45, -9, 21, -5, 18, -13, -8, -14, -5, 2, 10, 5, -31, 2, -12, 22, -1, 34, 4, -7, 3, 5, -8, 5, 6, -7, -5, -24, 16, -25, -57, -6, 15, -16, 1, 2, -6, -16, 9, 14, 6, 5, -26, 12, -32, 22, 27, -5, 2, 10, 17, -12, -41, 10, -11, 5, -9, -27, -5, -7, -74, -23, 7, -5, 4, 11, 16, -7, -3, 15, -15, -12, 15, 8, -19, -27, 18, -7, -18, 6, 13, -2, -86, 11, 29, 8, -28, -10, 16, -36, -74, 
  47, 62, -12, 56, 40, -18, 32, 10, 39, -19, 9, 46, 4, 38, 32, 12, 19, -32, 35, -10, -5, 53, -11, 13, 13, 0, 0, -15, 29, -47, 21, 23, 10, 48, 45, -19, 3, -25, 8, -15, -8, 30, 8, 28, 58, 17, 2, -41, 4, 5, -20, 35, -4, -16, -5, -22, -11, -21, 28, -18, -2, 21, 4, 43, 19, -56, -22, -38, -16, -27, 9, 35, -11, 51, 8, 16, 0, -41, 6, -18, -6, 33, 9, 9, -13, -31, 9, -28, 25, -16, -8, 45, 2, 49, 20, -64, -13, -39, 13, -26, -8, 20, -6, 34, 5, -1, 5, -42, 12, -10, -1, 35, -10, 0, -3, -19, 15, -28, 25, 9, 16, 39, -1, 32, 24, -42, 11, -50, 1, -19, -17, 13, 5, 17, -27, 15, 0, -35, 16, -13, 20, 46, -1, -3, 6, -10, -4, -38, 14, 17, 18, 19, 2, 7, 39, -56, 3, -37, -26, -14, -2, 6, 7, 37, 0, 12, -12, -21, 16, 3, -3, 51, -3, 5, -8, -4, 8, -11, 42, 9, 6, 12, 11, 20, 43, -30, -9, -45, -1, -19, -18, 34, -1, 21, -3, 25, -5, -29, 26, 6, -4, 65, 16, 17, 15, -19, 16, -23, 16, 7, 2, 33, 5, 32, 51, -43, -8, -25, -3, -21, -4, 17, 4, 9, -1, 30, -8, -42, 13, -1, 8, 40, 4, 10, 15, -18, 20, -40, 18, 5, -1, 39, -10, 26, 71, -53, -4, -33, -14, -27, 7, 26, 1, 19, 0, 56, 6, -43, 24, -15, -8, 43, 3, 1, 7, -14, 5, -29, 2, 8, 13, 53, -12, 29, 75, -38, -10, -45, -10, -33, 3, 46, 2, 32, -5, 7, 9, -48, 25, -5, 12, 31, 0, 3, 18, -19, 2, -32, -16, -1, 15, 47, -8, 18, 54, -29, 5, -36, -4, -35, -7, 22, -11, 31, -13, -25, 1, -27, 9, 6, 34, 29, -3, 9, 26, -41, 33, -30, -13, 33, 11, 37, -5, 18, 7, -42, -27, -53, 2, -28, 25, 28, 8, 51, -7, -31, 5, -25, -13, 1, 5, 42, -14, -2, -6, -38, 13, -64, -15, 32, 
  -101, 2, -17, -31, 10, 65, -47, 13, 34, -67, 6, 25, -16, 14, -36, 1, -14, 28, 16, 9, 3, -53, 9, -16, 26, 27, 23, 1, 7, 28, -10, -7, 11, 0, -33, -11, -23, 10, 15, -14, -16, 39, -13, -2, -28, -12, -14, 20, 1, -1, 6, -47, 16, -23, 10, 12, 12, 28, -11, 34, -3, -2, -14, -30, -29, -8, -3, 19, -14, -21, 0, 17, -5, 19, -53, 3, -33, 15, -10, -12, 14, -33, -8, -6, 18, 3, 13, -7, 3, 28, -19, -6, -9, -28, -23, 11, 7, 15, 9, 11, -6, 28, -2, 0, -57, 1, -36, 12, 11, -19, 18, -44, -4, 3, 4, 13, 35, 28, -4, 5, -19, -38, 3, -18, -8, 20, -14, 7, -12, -5, -7, 18, -4, -3, -78, -20, -29, 14, 8, -20, -10, -25, -7, -4, 13, 8, 9, 13, 3, 5, -18, -34, 11, -27, -52, 4, 12, 0, -10, 11, -10, 10, -4, -14, -61, -23, -7, 5, 11, -3, 11, -52, -12, 3, 18, 27, 10, 21, -6, 17, -10, -12, 7, -29, -30, 7, -9, -2, 2, -2, -19, 4, -15, -18, -87, -14, -24, -6, 15, 1, -8, -37, 5, -11, 4, 19, -6, 21, -13, 7, 15, -37, -11, -13, -52, -13, 17, 9, 7, 5, -14, -4, 4, -21, -99, 9, -15, -18, -1, -19, 11, -30, 9, 7, 14, 50, -6, 9, -30, 19, 25, -22, 14, -12, -53, 2, -5, 1, -4, 0, -29, -13, -7, -14, -60, 5, -14, 5, 6, -19, 10, -25, -12, 4, 12, 14, -11, 9, -12, 12, 29, -21, 3, -36, -29, -11, 5, 0, -14, 15, -23, 7, 4, -36, -66, -3, -12, -12, 11, -13, 14, -23, 2, -11, 10, 14, -8, 10, -1, -3, 24, -29, -3, -6, -19, 25, -8, -4, -15, 32, -36, -27, -13, -36, -12, 26, -16, 10, -10, -27, -9, -4, -2, -13, -17, 43, -8, -7, 8, 13, 21, -42, -3, -34, 9, -5, 0, 10, -4, 27, -27, -31, -10, -53, -51, 27, -6, -19, -20, -6, 4, -2, -10, 25, -9, 10, -10, 10, -27, 27, 
  48, -60, 4, -64, -56, -63, 7, -14, -65, 70, 17, -32, -13, 23, -24, -19, -11, 16, -47, -7, -3, -28, -7, -53, 3, -5, 14, -25, -13, 24, 18, -41, 5, -22, 21, 13, 12, 28, -14, 9, -17, -30, -5, 20, -44, -26, 8, 24, -19, -2, 18, 8, -11, -3, 11, -13, 32, 0, 24, 40, 16, -43, 1, -63, 10, 54, 15, 28, -13, 22, 21, -28, 12, 14, -66, -50, -17, 28, -38, 1, -11, 5, 6, -8, 4, -31, 12, 10, 5, 34, 0, -24, 10, -52, 6, 18, 32, 18, -2, 15, 19, -22, -12, 27, -88, -34, -17, 9, -24, -3, -6, -14, 2, -6, -5, -51, 27, -9, 18, 34, 22, -35, -12, -24, 16, 39, 25, 10, -17, 8, -10, -16, 7, 28, -58, -31, -20, 6, -43, -18, -14, -25, 10, -9, -7, -50, 2, 3, 0, 36, 28, -31, -10, -34, 18, 32, 25, -7, -5, -11, -12, -8, 11, 34, -45, -41, -5, 0, -16, 10, -1, -23, -8, -14, -16, -59, 6, -15, -10, 42, -7, -34, -13, -20, 19, 48, 22, 19, 1, 2, 14, -20, -2, 17, -66, -17, -3, 3, -31, 11, -9, -48, -16, -6, 0, -71, 8, 9, -11, 18, 10, -18, 13, -39, -1, 46, 5, 5, -13, -4, 7, -26, -3, 5, -63, -21, -13, -1, -12, -2, -6, -22, -6, -20, 2, -64, 7, -11, 10, 29, 18, -36, -14, -42, -3, 44, 24, 15, -12, -3, -2, -11, -11, 11, -47, -44, -6, 12, -27, -6, -30, -6, 1, -17, 4, -54, -4, 3, 19, 11, 16, -36, -1, -28, 14, 17, 15, 26, 0, -6, 16, -25, 0, 27, -58, -34, -5, 12, -46, -1, -19, 1, 4, -12, -30, -28, 3, -21, 21, -14, -1, -36, -8, -14, 11, 26, 22, 0, -4, 11, 20, -13, 8, -11, -60, -40, 10, -18, -37, 3, -34, 5, 14, 7, -40, -27, -44, 5, 12, -48, -8, -16, -13, -13, 12, 3, 37, 5, 6, -4, -5, -22, -2, -50, -93, 1, -12, -23, 6, -16, -20, -28, 4, 18, 25, -37, -29, 14, -17, -74, 
  -23, -68, 3, -40, 5, -58, -15, -22, -48, -10, -9, -36, -1, -33, -125, -45, 1, -25, -32, 6, -3, -9, -11, 30, -56, -126, -19, 13, -27, -19, 6, -11, 9, -32, -17, 0, 18, 5, 10, -10, -15, -34, 7, -39, -113, 14, 6, -14, -7, 9, -1, -8, -9, 21, -21, 26, -32, 30, -6, 3, 22, -45, 1, -46, 14, 7, 15, -9, -15, 24, -31, -7, 5, -27, -80, -29, -12, 0, -3, 6, 25, 8, -5, 13, 5, 30, -18, 23, -6, 15, 43, -34, 5, -39, -13, 19, 12, 5, -14, 53, -34, 3, -1, -29, -46, -15, -24, 5, 19, -12, 16, 23, 9, 35, -3, 15, -6, 28, -17, -14, 30, 0, -5, -7, -44, 16, 12, -12, -5, 30, -29, 2, 3, -11, -65, -43, 8, 0, -16, -24, 13, -6, 3, 0, 3, 29, -22, 7, -26, -32, -14, -3, 11, -27, -35, 0, 7, 13, -6, 26, -7, 15, 4, -12, -31, -46, -25, 6, -4, -30, 1, 13, -3, 28, -4, 16, 4, 21, 4, -16, 10, -21, 3, 2, -41, 17, 4, 0, 5, 21, -9, 2, 11, -10, -56, -50, -18, 0, -7, -20, -2, -17, -12, 14, 23, 25, 9, 14, -23, -8, -8, -2, 12, -22, -41, -9, 18, -6, -4, 30, -27, -5, -6, -17, -53, -31, -21, 0, -7, -19, 8, -12, 4, 32, 15, -1, 13, 14, 4, 18, -10, -25, -6, -19, -36, -11, 3, 1, -12, 2, -23, -5, -11, 3, -47, -28, -8, 7, 17, -2, 15, -18, 1, 2, -4, 11, 2, 20, -14, -15, -6, 0, 4, -34, -28, 13, 12, -5, -3, 12, -11, -5, 11, 12, -15, -22, -23, -1, 2, -13, 13, -18, -13, -8, 21, 8, 28, 8, -2, 10, 3, -4, 5, -24, -17, -12, -13, -7, -16, 11, -35, 6, 9, 10, -18, -5, -38, 19, 11, -1, 2, -16, -10, -3, 22, -19, 25, 12, 0, 37, -4, -11, 14, -22, -30, 22, 10, 7, -9, 12, -41, 9, -11, 37, -7, -41, -63, 30, -1, -29, -11, -58, 4, -16, 19, 12, 51, -10, 7, 26, 
  -60, -55, -12, -27, 16, -15, -21, -31, -25, -23, 28, -22, 16, -23, -92, -73, 12, -4, -16, 27, -33, -43, 5, -6, -47, -63, -41, 9, -42, -26, -52, 14, 12, -20, -62, -3, -23, -20, 23, -29, 12, -12, -16, -28, -127, -90, 11, -11, -13, 18, -3, -48, -6, 3, -18, 7, -45, -11, -17, -37, -48, 0, -6, -38, -42, -8, -18, -22, 10, -6, 8, -11, -11, -18, -32, -34, 23, -15, -5, 4, -12, -35, 7, 10, -30, 2, -45, 20, -43, -48, -38, 30, -8, -9, -31, 9, -7, -6, 27, 12, 32, -12, 4, -53, -16, -36, 37, -8, -15, 27, -7, -49, 0, -2, -18, 3, -44, 37, -23, -51, -15, 16, 4, -20, -23, 16, -17, 21, 29, 9, 34, -8, 14, -43, 0, 0, 25, 5, 11, 14, -25, -40, -14, 18, -15, 1, -52, 31, -32, -75, -23, 33, -6, 5, -37, 6, -16, 4, 24, 5, 26, -25, -12, -38, 35, -8, 13, 21, -2, 17, -27, -2, -11, 1, -40, -6, -32, 4, -4, -63, -41, 15, 12, -13, -25, -13, -6, 14, 17, 7, 21, -12, 3, -30, 43, -25, 23, -2, -12, 10, -24, -5, -2, -8, -23, -8, -20, 16, 6, -43, -19, 7, -16, 0, -64, -12, -1, 3, 15, -8, 22, -29, -1, -33, 69, -16, 20, 5, -4, 7, -11, 0, -15, -17, -46, -32, -16, 7, -4, -22, -13, 21, -3, 1, -68, 29, 8, 28, 8, -3, 28, -18, 15, -20, 74, -21, 36, 9, -10, 12, -12, -16, 8, -2, -56, 3, -18, 16, -12, -8, -38, -12, -9, 0, -60, 24, 9, 10, 9, 11, 7, -25, 0, -30, 93, -10, 11, 25, -19, 4, -19, 1, -15, -13, -32, -6, -34, -1, 7, -20, -11, -30, 12, 1, -61, 23, 9, 28, 9, 11, 1, -26, -14, -17, 68, -5, 8, 4, -22, -1, -28, 6, 4, -15, -50, -28, -17, 7, 12, 3, -2, -10, 14, -11, -66, 17, -9, 33, -10, -11, 8, -37, -10, -15, 95, -4, 14, 28, -25, 1, -11, 21, -3, -38, -42, 18, -6, 20, 25, 3, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 6,360 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0078665958717465401, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[10] = { 894, 1737, -32, 1389, 2103, -444, 816, -1175, 864, -331, };
const TfArray<1, int> tensor_dimension7 = { 1, { 10 } };
const TfArray<1, float> quant7_scale = { 1, { 0.00027107950882054865, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[10*1*1*8] = { 
  /* [0][0][][] */ 54,-80,-40,8,67,44,96,-95, 
  /* [1][0][][] */ -26,-67,53,72,43,8,-53,-89, 
  /* [2][0][][] */ -11,-61,-3,64,-31,-36,-20,12, 
  /* [3][0][][] */ 49,-11,79,9,-68,69,-44,-85, 
  /* [4][0][][] */ -3,68,-70,26,-58,93,-44,-56, 
  /* [5][0][][] */ -63,127,-62,82,26,-64,-73,100, 
  /* [6][0][][] */ 81,19,-64,-47,88,85,11,-32, 
  /* [7][0][][] */ 13,98,66,61,10,66,104,-14, 
  /* [8][0][][] */ 18,27,39,35,73,20,-106,-44, 
  /* [9][0][][] */ 62,-113,-45,-52,75,90,3,51, 
};
const TfArray<4, int> tensor_dimension8 = { 4, { 10,1,1,8 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0080212689936161041, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[8] = { 748, 359, 754, 1186, 412, 1667, -450, -848, };
const TfArray<1, int> tensor_dimension9 = { 1, { 8 } };
const TfArray<1, float> quant9_scale = { 1, { 0.0002652975672390312, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[8*1*3*1] = { 
  /* [0][0][][] */ -7, 62, 21, 
  /* [1][0][][] */ -127, -123, 31, 
  /* [2][0][][] */ 80, 52, -90, 
  /* [3][0][][] */ -118, -21, 24, 
  /* [4][0][][] */ 99, -62, 3, 
  /* [5][0][][] */ -48, 59, 26, 
  /* [6][0][][] */ 30, 108, 6, 
  /* [7][0][][] */ 61, -30, 62, 
};
const TfArray<4, int> tensor_dimension10 = { 4, { 8,1,3,1 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0078618982806801796, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const TfArray<4, int> tensor_dimension11 = { 4, { 1,1,72,1 } };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,72,8 } };
const TfArray<1, float> quant12_scale = { 1, { 0.033795088529586792, } };
const TfArray<1, int> quant12_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,72,1,8 } };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,36,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,1,36,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,36,10 } };
const TfArray<1, float> quant16_scale = { 1, { 0.048787206411361694, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfArray<2, int> tensor_dimension17 = { 2, { 1,360 } };
const TfArray<2, int> tensor_dimension18 = { 2, { 1,6 } };
const TfArray<1, float> quant18_scale = { 1, { 0.18547186255455017, } };
const TfArray<1, int> quant18_zero = { 1, { 56 } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&quant18_zero, 0 };
const TfArray<1, float> quant19_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 11,10,9 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 12,2 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 13 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 14,3 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 15,8,7 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 16,4 } };
const TfArray<1, int> outputs6 = { 1, { 17 } };
const TfLiteFullyConnectedParams opdata7 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs7 = { 3, { 17,6,5 } };
const TfArray<1, int> outputs7 = { 1, { 18 } };
const TfLiteSoftmaxParams opdata8 = { 1 };
const TfArray<1, int> inputs8 = { 1, { 18 } };
const TfArray<1, int> outputs8 = { 1, { 19 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension12, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension14, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension16, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension17, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension18, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 20, };
const size_t tflNodes_subgraph_index[] = {0, 9, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  19, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_792000_36_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 20;
  for (size_t i = 0; i < 20; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_invoke() {
  for (size_t i = 0; i < 9; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_36_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
