/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 12.05.2026 18:06:02

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 2704;
#else
constexpr int kTensorArenaSize = 1680;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,72 } };
const TfArray<1, float> quant0_scale = { 1, { 0.07733609527349472, } };
const TfArray<1, int> quant0_zero = { 1, { -12 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 72, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 72, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 36, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data4[2] = { -1, 360, };
const TfArray<1, int> tensor_dimension4 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[6] = { -154, 299, -202, -49, -110, -169, };
const TfArray<1, int> tensor_dimension5 = { 1, { 6 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00055431149667128921, } };
const TfArray<1, int> quant5_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[6*360] = { 
  -7, 29, -9, 13, -30, 10, -5, 0, -4, -6, -8, 0, -13, -18, 7, 24, 6, -4, 11, -6, -19, -7, 12, 15, -13, -8, -24, 8, -9, -15, 1, 19, 5, 13, -20, -5, -25, -14, -4, 12, 1, -5, 14, -16, 20, 21, 7, 14, -10, 13, -11, -27, 6, -1, -26, -19, -8, -1, -17, -37, 15, 33, -11, 25, -18, -39, 4, -15, 17, 15, 8, -10, -4, -33, 40, 28, 6, 7, 7, 20, -2, -44, -2, 3, -40, -20, -11, 16, -29, -23, 16, 25, 1, 13, -45, -8, 0, -9, 19, 9, 6, -12, 14, -12, 26, 19, 33, -1, 16, 11, -13, -13, -17, 13, -25, 0, -11, 7, -13, -42, -6, 13, 15, -2, -19, -17, 6, -3, 14, 16, 3, 1, -15, -7, 28, 20, 5, 18, 4, 24, -36, -44, 6, 6, -43, -5, -34, 12, -14, -39, -8, 26, -13, 8, -28, 12, -22, -15, 14, 0, 38, 20, 8, -21, 7, 10, 25, 11, -12, 1, -26, -15, 12, 1, -2, 7, -28, -4, -3, -24, -21, 18, -2, -2, -24, 6, -3, -7, 8, -15, 5, 20, -11, -6, -16, -2, 4, 2, 8, 14, 3, -37, 1, -4, -25, -21, -5, 15, 2, -17, -28, 15, -16, 7, -15, 24, -18, -25, 17, -2, 22, 10, 2, -8, -7, 6, 8, 16, -11, 2, -10, -35, 14, -6, -4, 5, -19, 13, -10, 0, -8, 8, -13, -5, -26, 6, -32, -14, -8, -20, 18, 29, -11, 11, 8, 24, -15, 15, 7, 5, -6, -12, 9, 14, -14, -1, -8, 21, -22, -35, -17, 21, -6, 8, -18, -12, -22, -15, -2, 8, 20, 8, 1, -3, 13, 11, 26, 8, -2, 12, 6, -16, 4, 12, -7, 0, -25, 18, -26, -32, -3, 22, -16, -1, -3, -14, -18, 12, 14, 9, 20, -11, 12, -33, 14, 27, -6, 7, 6, 26, -17, -23, 10, -5, -19, -28, -31, -1, -10, -45, -24, 2, -5, 4, -2, 9, 0, -1, 10, -10, -7, 16, 8, -14, -14, 27, -7, -10, 6, 18, -28, -60, 11, 37, 2, -3, -16, 22, -19, -48, 
  25, 3, -18, 24, 19, -6, 24, 1, 19, 9, -30, -27, 4, 12, 25, 36, 34, -25, 19, -34, -2, 12, -11, -16, -19, -20, 17, -24, 15, -10, 11, -9, 10, 42, 22, 4, 4, 10, 2, -18, -42, -36, 8, 6, 40, 14, 15, -21, -5, -14, -31, 1, -4, -34, -18, -19, 8, -14, 33, 6, 0, 2, 4, 29, -2, -22, -6, 5, -11, -18, -25, -50, -11, 24, 50, 32, 16, -25, -19, -38, -22, 3, 9, -20, -20, -31, 30, -34, 35, 2, -7, 14, 1, 33, 13, -35, 5, -13, 10, -14, -43, -54, -6, 12, 66, 4, 22, -38, -9, -36, -23, -5, -10, -39, -5, -8, 35, -53, 33, 15, 15, 13, -1, 35, 14, -19, 26, -14, 5, -13, -62, -80, 6, -5, 46, 38, 12, -29, -1, -50, 3, 14, -1, -56, 6, -3, 18, -68, 22, 27, 17, 1, 2, 25, 36, -47, 17, 2, -21, -9, -27, -108, 6, 15, 57, 20, 7, -16, -4, -10, -15, 21, -3, -44, -16, -4, 29, -40, 40, 19, 9, 1, 10, 45, 14, -36, 6, -4, 12, -4, -39, -85, -1, 3, 56, 43, 19, -13, 10, -7, -22, 36, 15, -29, 13, -9, 39, -49, 18, 9, 6, 20, 4, 50, 30, -52, 10, 13, 14, -4, -27, -122, 4, -8, 65, 54, 19, -27, -10, -14, -11, 11, 3, -32, 15, -18, 46, -71, 24, 11, 2, 2, -10, 29, 31, -56, 13, -2, -9, -11, -28, -90, 1, 7, 62, 64, 17, -34, 5, -47, -16, 6, 3, -58, 5, -12, 40, -57, 12, 24, 7, 0, -12, 17, 59, -11, 7, -19, -12, -24, -49, -72, 2, 14, 59, 39, 12, -42, 4, -51, -2, -10, -1, -42, 12, -7, 32, -55, -2, 8, 6, -13, -8, -6, 42, 1, 25, -20, -9, -24, -61, -59, -11, 11, 38, -9, -7, -29, -12, -44, 15, -5, -3, -28, 7, -31, 48, -47, -1, 30, 9, -7, -5, -11, 10, -17, -8, -36, -2, -15, -21, -51, 8, 19, 28, -36, -2, -18, -41, -44, -32, -10, -14, -57, -6, -40, 27, -86, -3, 13, 
  -67, -10, -15, -41, -2, 27, -26, -5, 14, -34, 9, 19, -16, 24, 2, -3, -30, 24, 0, -8, -4, -32, 9, -20, 17, 12, 20, -6, 4, 16, -7, -12, 10, -11, -20, -7, -17, -4, 9, -15, 0, 47, -12, -10, -20, -31, -27, 2, -10, 0, 6, -16, 16, -32, 5, 15, 1, 21, -14, 31, -12, -17, -14, -35, -12, 4, -8, 14, -17, -31, 2, 24, -4, 22, -47, -7, -41, 13, -13, -18, 19, -18, -8, -20, 35, 27, 15, -9, 10, 29, -13, -2, -10, -17, -27, 12, 0, 23, 12, 8, 0, 42, -3, 9, -55, -2, -44, 25, 17, -12, 24, -16, -4, -8, 1, 20, 32, 38, 0, 7, -20, -37, 3, -3, -14, 21, -14, 7, -8, -9, -5, 21, -4, 8, -52, -18, -35, 24, 8, -14, 2, -5, -8, -22, 10, 12, 7, 13, 6, 21, -21, -37, 10, -30, -44, 11, 7, -7, -20, 7, -15, 31, -5, 2, -18, -23, -27, 10, 5, -14, 24, -30, -12, -13, 12, 18, 12, 21, 2, 28, -16, -16, 7, -23, -25, 12, -16, -3, -10, -13, -11, 19, -15, -9, -37, -24, -27, -3, 13, 12, -1, -21, 4, -21, -2, 4, -3, 20, -1, 16, -3, -29, -12, -3, -34, 0, 5, 14, 1, -14, -9, 26, 4, -12, -47, -7, -27, -12, 1, -10, 13, -5, 9, 6, 9, 23, 0, 14, -12, 27, 8, -13, 14, -1, -39, 12, -9, 9, -8, -24, -12, 12, -7, -7, -32, -3, -17, 9, 8, 4, 8, 11, -12, 7, 11, -4, -9, 12, 2, 5, 4, -5, 3, -27, -16, -1, -9, 5, -10, -19, 7, 42, 4, -20, -37, -11, -21, -7, 14, 23, 16, -4, 2, -14, 8, -4, 1, 14, 8, -2, 8, -27, -3, -3, -18, 22, -22, -5, -22, 13, -3, 6, -13, -26, -30, 10, -19, 10, -10, 13, 1, 5, -2, -5, -12, 21, 9, -3, 10, 14, 2, -53, -3, -26, 0, 0, -15, 8, -2, 4, 4, 11, -10, -22, -19, 29, -7, -4, -5, 22, 7, 3, -10, 36, 7, 0, -8, 7, -19, 5, 
  26, 2, 9, -6, -26, -36, -15, 14, -28, 27, 27, -22, -14, 17, -27, -19, -15, 5, -31, 2, -6, 7, -7, -22, 5, -9, -2, -2, -17, 2, 11, -9, 5, -7, 28, 4, 11, 10, 4, 21, 7, -7, -5, 26, -36, -22, 7, 10, -9, 16, 5, 21, -11, 8, -3, 10, 1, -4, 12, 13, 6, -11, 1, -12, 14, 38, 1, 16, -3, 20, 25, -12, 12, 23, -64, -46, -22, 11, -20, 2, -17, 27, 6, 0, -10, -1, -20, 8, -3, 16, 3, -3, 10, -10, 14, 9, 27, 20, 3, 27, 20, -24, -13, 21, -77, -36, -27, -7, -24, -2, -21, 21, 2, 7, -17, -23, -9, -2, 9, 5, 30, -5, -12, 0, 6, 36, 31, 9, -5, 31, 2, -26, 7, 17, -43, -37, -16, -3, -49, -5, -30, 12, 10, 14, -26, -29, -39, 16, -9, -6, 39, 4, -10, -12, 22, 36, 36, -2, 16, 12, -9, -21, 10, 28, -50, -55, -2, -5, -12, 16, -24, 24, -8, 12, -14, -24, -30, -3, -5, 6, 6, -13, -13, -5, 34, 53, 32, 10, 9, 22, 12, -18, -2, 11, -50, -47, -8, -7, -28, 7, -21, 5, -16, 21, -6, -38, -23, 21, -7, -11, 23, 3, 12, -22, 21, 46, 9, -4, -7, 16, 7, -20, -3, -7, -47, -36, -15, -9, -3, 3, -19, 24, -5, 5, -4, -14, -25, 2, 6, 1, 29, -17, -14, -25, 20, 50, 31, 5, -6, 16, -2, -10, -11, 0, -30, -53, -6, 6, -22, -2, -39, 23, 1, 4, 10, -12, -32, 12, -4, -9, 26, -4, -1, -10, 31, 27, 19, 21, 7, 8, 18, -29, 0, 18, -48, -54, -2, 10, -39, 7, -30, 31, 3, 4, -29, -7, -22, -24, 1, -22, 2, -12, -7, 3, 20, 18, 17, -5, -5, 13, 26, -11, 9, -3, -38, -31, 14, -3, -19, 11, -25, 24, 14, 12, -34, -13, -53, 8, 6, -26, -17, -24, -14, -4, 11, 12, 23, 18, -5, -12, -1, -15, -2, -32, -62, 5, -7, -18, 18, -9, -5, -11, 4, 5, 25, -12, -25, 8, -20, -21, 
  14, -127, 2, -5, -4, -5, 1, 8, -18, 1, 13, 20, -1, -7, -64, -61, -8, -26, -17, 33, 11, 0, -11, 25, -4, -11, -2, 4, -15, 1, 12, -48, 10, -17, -6, -2, 4, 3, -2, -17, -15, 2, 7, -1, -10, 1, 3, -9, -2, 17, 5, -2, -9, 16, 1, 14, -2, 19, -2, 10, 13, -77, 1, -33, 11, -4, -1, -23, -29, 0, -13, 32, 4, -7, -35, -32, -14, -3, 7, 30, 32, 26, -5, 15, 4, 6, -11, 16, -13, 17, 8, -59, 5, -26, 12, 20, -11, -11, -26, 9, -27, 32, 0, -14, -33, -6, -40, -7, 20, 0, 31, 41, 9, 35, -3, -14, 5, 24, -14, -1, 2, -21, -5, -2, -14, 15, -9, -24, -30, -15, -20, 44, 3, -2, -38, -23, -1, -10, -10, -8, 26, 9, 2, 6, 3, 0, -9, 11, -18, -12, -34, -15, 11, -24, -11, -9, 0, 7, -18, 0, -5, 41, 5, -3, -14, -16, -26, 3, 2, -16, 12, 36, -3, 35, -10, 4, 6, 21, 16, 3, -6, -28, 3, 0, -12, 14, -5, -5, -5, -2, -16, 29, 11, 0, -32, -30, -34, -7, -11, -28, 15, 7, -12, 9, 14, 13, 11, 9, -16, 15, -16, -7, 12, 0, -25, -15, 8, -2, -15, 11, -33, 17, -6, -7, -24, -12, -29, -7, -1, -26, 22, 21, 4, 31, 7, -6, 12, 15, 14, 26, -8, -24, -6, -2, -24, -10, -3, 6, -12, -5, -23, 4, -11, 8, -29, -18, -15, -1, 14, -6, 28, 3, 1, -2, -13, 6, -1, 21, -6, -7, 7, -9, 4, -13, -28, 6, 4, -4, -11, 10, -13, 7, 11, 16, -18, -9, -25, -12, 5, -24, 15, 12, -13, -9, 23, 11, 15, 12, 4, -1, 11, -4, 5, -5, -11, -4, -19, -6, -8, 4, -41, 11, 8, 18, -2, 11, -43, 9, 13, -14, -8, 0, -10, -11, 29, 1, 10, 8, 4, 21, 1, 8, 14, 13, -22, 12, 6, 4, 1, 10, -45, 10, -10, 32, -33, -28, -65, 12, -6, -27, -2, -13, 4, -16, 11, 14, 46, 0, 2, 16, 
  -34, -40, -12, -39, 12, -14, -2, -21, -15, -18, 25, 6, 16, -6, -51, -51, -3, -3, -7, 22, -42, -9, 5, -1, -44, -29, -43, 9, -10, -27, -38, -16, 12, -30, -20, 19, -8, -17, 14, -18, 14, 6, -16, -17, -32, -40, 4, -2, -7, 20, -11, -24, -6, 12, -14, 9, -50, -5, -2, -36, -43, -34, -6, -54, 7, 19, -4, -18, 4, 0, 11, 11, -12, -3, -17, -18, 21, -3, 7, 8, -15, -13, 7, 25, -26, -9, -38, 30, -25, -29, -52, -7, -8, -16, 14, 35, -4, -14, 21, 8, 32, 32, 3, -30, -29, -23, 28, -13, 2, 28, -6, -51, 0, 16, 2, -17, -33, 38, -21, -27, -34, -10, 5, -28, 4, 19, -31, -3, 15, -13, 37, 55, 14, -17, -30, -14, 9, -9, 21, 12, -8, -34, -14, 33, 3, -28, -39, 31, -34, -38, -35, 3, -6, -6, -7, 4, -35, -16, 10, -20, 31, 42, -13, -22, -6, -10, -3, 8, 7, 22, -15, -26, -11, 23, -8, -4, -20, 11, -11, -37, -45, -3, 12, -29, 1, -14, -14, -4, 12, -2, 27, 46, 3, -18, -14, -1, 19, -2, 0, 15, -25, -46, -3, 17, 12, -15, -14, 19, -9, -37, -13, 2, -16, -24, -40, -25, -5, -16, 11, -6, 31, 37, -1, -16, -1, 4, 14, 0, 7, 13, -16, -30, -16, 9, -20, -18, -22, 10, -24, -14, -11, 30, -3, -14, -36, 1, 2, 0, 6, 1, 47, 51, 15, -3, -7, -12, 37, 10, 8, 25, -27, -33, 8, 26, -34, -5, -32, 20, -29, -19, -23, 15, -9, 5, -31, -21, 12, -6, 14, 25, 16, 14, 0, -20, 14, -10, 22, 19, 0, 18, -38, -20, -14, 15, -19, 0, -49, 3, -8, -43, -1, -4, 12, 9, -31, 2, 9, 12, 20, 17, 13, 14, -15, -9, 9, 5, 22, -7, 5, 17, -50, -18, 4, 13, -9, -3, -29, 8, 6, -31, 16, 26, 14, -5, -30, -4, -3, 3, 0, 1, 27, 12, -10, 7, 25, -8, 23, 15, -8, 21, -15, 9, -3, 15, -27, -2, -34, 29, 0, -18, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 6,360 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0078171910718083382, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[10] = { 180, 360, 14, 404, 802, 298, 558, -513, 376, -136, };
const TfArray<1, int> tensor_dimension7 = { 1, { 10 } };
const TfArray<1, float> quant7_scale = { 1, { 0.00051073497161269188, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[10*1*1*8] = { 
  /* [0][0][][] */ 59,-81,-9,17,96,45,109,-74, 
  /* [1][0][][] */ -18,-100,99,88,79,-6,-6,-35, 
  /* [2][0][][] */ -13,-58,-1,62,-29,-35,-20,13, 
  /* [3][0][][] */ 57,35,87,19,-100,69,-12,-50, 
  /* [4][0][][] */ -3,79,-77,-8,-32,72,-47,34, 
  /* [5][0][][] */ -30,89,-72,78,10,-39,-12,87, 
  /* [6][0][][] */ 77,30,-62,-68,83,76,-19,-25, 
  /* [7][0][][] */ 17,57,67,83,-13,72,127,-58, 
  /* [8][0][][] */ 28,24,32,28,83,23,-93,-6, 
  /* [9][0][][] */ 39,-85,-11,9,98,74,1,16, 
};
const TfArray<4, int> tensor_dimension8 = { 4, { 10,1,1,8 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0083158314228057861, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[8] = { 370, 672, -73, -13, 313, 508, -155, 308, };
const TfArray<1, int> tensor_dimension9 = { 1, { 8 } };
const TfArray<1, float> quant9_scale = { 1, { 0.00057421252131462097, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[8*1*3*1] = { 
  /* [0][0][][] */ -31, 64, -4, 
  /* [1][0][][] */ -110, -98, 30, 
  /* [2][0][][] */ 100, 78, -110, 
  /* [3][0][][] */ -116, -4, -7, 
  /* [4][0][][] */ 127, -81, -17, 
  /* [5][0][][] */ -36, 56, -13, 
  /* [6][0][][] */ 9, 121, -8, 
  /* [7][0][][] */ 15, -65, 49, 
};
const TfArray<4, int> tensor_dimension10 = { 4, { 8,1,3,1 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0074248965829610825, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const TfArray<4, int> tensor_dimension11 = { 4, { 1,1,72,1 } };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,72,8 } };
const TfArray<1, float> quant12_scale = { 1, { 0.061417188495397568, } };
const TfArray<1, int> quant12_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,72,1,8 } };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,36,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,1,36,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,36,10 } };
const TfArray<1, float> quant16_scale = { 1, { 0.070909291505813599, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfArray<2, int> tensor_dimension17 = { 2, { 1,360 } };
const TfArray<2, int> tensor_dimension18 = { 2, { 1,6 } };
const TfArray<1, float> quant18_scale = { 1, { 0.33470895886421204, } };
const TfArray<1, int> quant18_zero = { 1, { 74 } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&quant18_zero, 0 };
const TfArray<1, float> quant19_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 11,10,9 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 12,2 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 13 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 14,3 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingValid, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 15,8,7 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 16,4 } };
const TfArray<1, int> outputs6 = { 1, { 17 } };
const TfLiteFullyConnectedParams opdata7 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs7 = { 3, { 17,6,5 } };
const TfArray<1, int> outputs7 = { 1, { 18 } };
const TfLiteSoftmaxParams opdata8 = { 1 };
const TfArray<1, int> inputs8 = { 1, { 18 } };
const TfArray<1, int> outputs8 = { 1, { 19 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension12, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 576), (TfLiteIntArray*)&g0::tensor_dimension14, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 288, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension16, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension17, 360, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 368), (TfLiteIntArray*)&g0::tensor_dimension18, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[9] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 20, };
const size_t tflNodes_subgraph_index[] = {0, 9, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  19, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_792000_43_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 20;
  for (size_t i = 0; i < 20; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_43_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_43_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_43_invoke() {
  for (size_t i = 0; i < 9; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_43_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
