/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 14.10.2025 09:29:35

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1440;
#else
constexpr int kTensorArenaSize = 416;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,72 } };
const TfArray<1, float> quant0_scale = { 1, { 0.031372550874948502, } };
const TfArray<1, int> quant0_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[6] = { 18, 37, 82, 171, -91, -112, };
const TfArray<1, int> tensor_dimension1 = { 1, { 6 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0007075442117638886, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[6*20] = { 
  41, 53, -56, 31, -87, 60, 43, 58, -37, 33, -66, 65, -85, 26, -67, 18, -34, -89, 34, -78, 
  45, -18, -127, 39, 29, -53, -26, -75, 11, -112, 26, 8, 42, 78, -2, 58, 38, -68, 79, -93, 
  -74, 61, -22, -51, 63, 45, -54, 3, 35, 26, 49, 31, -121, 25, 48, 6, -57, 90, -10, -25, 
  34, -48, -9, -44, 83, -11, -55, 18, -83, 33, 57, 10, -44, -38, -35, -54, -16, -41, -53, 83, 
  33, -39, 33, -63, -68, 21, 36, 45, 90, 40, -10, -27, 0, 75, -54, -52, 72, -53, -75, 21, 
  -26, -4, -72, -50, -9, -85, 58, 10, -62, 45, 35, -53, 48, 25, 3, 7, -43, 47, 17, 44, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 6,20 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0069332467392086983, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[20] = { 63, -151, 131, 183, 570, 208, -239, 414, 129, 415, -227, -82, 225, -15, 63, 177, -195, 159, 227, 4, };
const TfArray<1, int> tensor_dimension3 = { 1, { 20 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00030676022288389504, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[20*20] = { 
  4, -71, 74, 102, -15, 6, 45, 58, -48, -19, 72, 55, -96, 50, -66, 67, -26, 78, 0, 54, 
  -43, 36, 21, -47, -65, -40, 29, 36, -37, -34, -5, -75, 56, -49, -55, 59, -46, 2, -31, 34, 
  5, -15, -51, -26, -5, 39, -5, -68, 66, -18, -16, -3, 116, -9, 7, 29, 27, 8, -5, -60, 
  23, 12, -68, -56, -12, 68, -49, 16, -65, 39, 63, -25, -13, 15, -45, 59, 28, 37, -67, 47, 
  13, -120, -40, -15, -48, 86, -29, 47, 9, 45, -80, 96, -36, 26, 59, 55, -96, 75, -56, 24, 
  -57, -35, -17, 12, -30, 69, -12, 0, -39, -33, -74, 41, 4, -2, 10, -89, 56, 34, -33, 33, 
  46, 51, 49, 21, -9, 35, -33, -8, 49, -21, 33, -24, 57, -63, -89, -54, 30, 26, 32, 49, 
  9, 89, 46, 113, 113, -20, 94, -24, 88, 46, 30, -21, 115, -22, -2, -17, 127, -55, 40, 87, 
  46, 72, 71, -40, -4, 61, 24, -20, -36, -8, 49, 18, 97, 61, 44, -28, 51, -84, 37, -65, 
  59, 63, 115, 46, 88, -18, 10, 75, 54, 40, 87, -45, 111, -31, 85, 38, 31, -42, 20, 0, 
  -59, 1, -7, -81, -39, 4, 61, -55, -21, 11, -66, 2, 15, 47, 22, 36, -55, -74, -6, -54, 
  -76, 35, -32, -63, 12, -41, 12, 53, 16, -20, -39, 29, 25, -48, -31, -15, -63, -17, 32, 0, 
  -50, 109, -48, 23, -8, 42, -89, -53, -40, -83, 55, -46, -51, 48, 7, 65, -2, 70, 10, 28, 
  1, 21, 28, -46, 42, 28, -74, -51, -58, 61, 89, -19, -74, 21, 3, 75, 54, -2, 66, -22, 
  54, -27, 11, -30, 37, 46, 2, -92, 88, 16, -23, -50, -69, 41, -54, 38, -33, 60, -70, -20, 
  49, 27, -98, 23, -13, 52, 29, -38, 29, -29, 44, 5, -3, 8, -73, 54, -86, 52, 9, 66, 
  13, -7, 82, 33, -1, 6, 19, -12, -9, 6, 32, -71, 50, 40, 60, 9, 36, -46, 41, -77, 
  78, 69, 47, -77, -1, 88, -30, 20, 39, 42, 17, -31, 74, 77, -17, -9, -82, -41, 47, -14, 
  32, 18, 0, -37, 24, 41, -73, 62, 32, -46, -66, 52, -79, -58, -62, 83, -10, -39, 55, 67, 
  -55, 23, 101, 37, -92, -2, -29, 29, 109, 76, -58, 10, -7, -15, -5, -61, -31, 72, -16, 40, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 20,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0052466029301285744, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 261, 475, 256, 817, 135, 794, 380, 444, 355, -21, 73, 763, 674, 539, 380, 537, 959, 582, -260, 625, };
const TfArray<1, float> quant5_scale = { 1, { 0.00012523155601229519, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*72] = { 
  16, -32, -1, 60, -6, 33, 25, -57, 24, -47, -14, 29, -55, -60, -12, 57, -3, 43, -28, -53, 53, -13, 27, 12, -53, 21, -22, -24, -54, -43, 23, 15, 58, -42, -57, 50, -27, 52, 18, -27, 41, 15, -34, 11, -31, 64, 5, 71, -35, -22, 5, -55, 49, 1, -52, 72, 75, 46, 107, 54, 20, 23, 24, -50, 43, -26, -3, 79, 66, -11, 73, -45, 
  -113, -1, 68, -31, -15, 36, -19, 27, 53, 23, -27, 49, -10, 24, 73, -48, 58, 72, 48, -38, 29, -23, 38, 29, 24, 22, 31, 46, -19, -17, -7, 49, 72, 67, 36, -2, -41, -9, 32, -16, -33, -28, 82, 31, 43, 13, 38, -47, 38, -7, -67, 30, 1, -53, 26, -69, -85, 85, 48, -85, 26, 39, -78, 23, -28, -65, 68, -73, -20, -7, 58, -81, 
  -10, 37, -35, -94, 58, -8, -9, 95, 85, -51, 14, 37, -87, 84, -8, 7, 69, 65, -27, 64, 82, -78, 60, -37, -7, 2, 63, 17, -21, -54, -48, 56, 17, -61, 4, -36, -65, 9, 25, -52, 34, 24, -63, -12, 18, -24, -32, -51, 3, -26, 38, -34, -22, -4, 11, -74, 3, -13, -24, -21, 34, -50, -18, -19, -37, 20, -20, -52, -43, -56, -9, -79, 
  -79, 70, -50, 34, 33, 43, -21, 99, 35, -70, 92, 48, 19, 79, 36, -28, -13, -12, 3, 70, -21, 4, -18, 5, 17, 40, -15, 19, 51, 67, -53, 32, 72, -58, 41, 18, 28, -68, 31, 11, -71, 65, -30, 21, 83, -78, -16, -14, 10, 17, -14, -30, -26, -38, -13, -77, -32, -89, -76, 2, 30, -33, 62, 13, -95, -53, -3, -110, -29, -102, -26, -19, 
  15, 8, -24, -72, -57, -76, 15, -31, -55, 2, -39, -12, -67, -54, -67, 10, 12, 21, -28, -32, -22, 34, -21, -15, -43, 4, 51, 21, -53, -41, 6, -30, 73, -68, -9, -16, -51, -47, 36, 1, 15, 43, -93, -12, 59, -76, 66, 62, -50, 67, 63, 9, -17, 11, -52, 100, 70, 12, 98, 66, -95, -7, 82, 16, 52, 60, -72, 116, -37, -63, -3, 36, 
  10, 6, 55, 21, -56, -17, 35, 38, 7, 41, -79, 10, -41, 15, 43, 16, -72, 46, -4, -12, -22, -36, -25, -6, 60, -22, 41, 5, -23, 85, 2, -3, 71, -26, 17, -31, 57, -32, 47, 71, 54, 37, -28, 1, 23, -47, -36, -29, 12, 49, 68, 2, 27, -16, 37, 52, 31, 1, 64, 21, 27, -31, 62, -34, 6, 18, -2, 72, 71, 55, 79, -14, 
  7, 15, -25, -59, -21, -62, -50, 68, -20, -27, 28, -2, -34, 46, 24, -43, -26, -34, 36, 40, -40, -7, -39, 27, -42, -25, 49, -70, 22, 5, 24, -87, -11, -25, -75, 19, -76, -1, -56, 46, -35, 21, -23, -24, -24, -73, 36, -27, -23, -40, -34, 39, -76, 52, 9, -25, 19, 43, 9, -13, -48, -19, 50, -51, 16, 26, -71, 31, -34, -54, 0, 74, 
  66, -17, 9, 69, 97, 9, 31, 69, -32, 59, 28, 48, -26, 59, -50, -67, 6, -29, -52, 70, 59, -54, -33, 6, -34, 44, -10, -4, -85, 2, -1, 32, 28, -63, -52, -54, -17, -13, 52, -28, -39, 38, 59, 33, 45, -9, -14, -32, -36, 12, -24, -16, -30, 43, -18, -63, -21, 49, 18, -41, -32, -40, 56, -30, 16, 46, 33, -40, -11, 87, -58, 24, 
  49, 44, 58, -6, -67, 55, 0, -60, 8, -5, -25, 53, 33, -37, 30, -45, 13, -4, 39, -12, 82, 18, 19, 48, 13, -4, 67, -30, 14, -31, 14, -94, 16, -20, -70, 9, -71, 45, -17, -8, -36, -7, -68, -27, -30, 14, -14, 10, -34, 37, -56, -58, 80, -51, 41, 56, -7, 45, 46, -51, 66, 47, 12, 16, 55, -115, 107, 95, -21, 26, 20, -79, 
  -19, 35, -18, 14, -38, 50, -37, 3, -28, -49, -47, -25, -61, -15, -34, 50, -5, 33, 46, -36, -23, 37, 25, 43, 52, 62, -14, 4, 25, 22, -39, 11, -44, -13, 78, 19, 28, 87, -5, -8, 49, 36, -51, 34, -24, -80, 39, 20, 43, -59, 27, 52, -72, -63, -42, -1, 29, 10, -70, 18, -46, -44, -35, 63, -4, 2, -38, -20, -38, 55, -43, 50, 
  26, 31, 33, -97, -41, -23, 4, 21, -5, -3, -40, 17, 1, -43, 26, -46, 5, -6, 17, 18, -62, 23, -57, 40, 47, -12, -38, -25, 40, 33, -70, -50, -60, -26, 61, 40, -32, -60, -69, 4, 8, -31, -10, -44, -46, 30, -14, -80, 23, 7, -31, -53, -30, -11, 32, 37, -44, -40, -2, -8, -3, 10, 45, 14, 10, -54, -91, 30, 35, -17, 61, 16, 
  21, 7, 81, 1, -59, -39, 81, -34, 67, -3, 47, 77, 38, 61, -14, 24, -25, -15, 51, 5, -7, -25, 65, 5, 1, 21, 38, 11, 49, 24, -21, -39, 7, -39, -20, -13, -56, -20, 14, 21, 5, 44, 45, -36, -41, -22, -16, 20, -46, -29, -54, 49, -8, 26, 68, 7, 35, 4, -22, -41, 71, 5, 23, 9, 28, 79, 70, -32, 34, 15, -89, 52, 
  -59, -93, -3, -37, 0, -46, -51, -108, -45, 25, -57, -54, 16, 4, -13, 37, -4, -16, 37, -20, 25, 16, -33, 34, 8, -14, 3, -60, 63, -14, -67, 42, -54, 17, 73, 46, 20, -18, -33, -61, 2, 42, -78, 16, -22, -62, 127, 78, -64, 127, 84, -117, -4, 47, -102, -5, -12, -45, 37, 56, -89, -7, -30, -28, 52, 24, -27, 61, 11, -22, 35, -29, 
  31, -113, 13, 9, 13, 102, -36, 20, 27, 26, -20, 53, 60, 1, 23, -40, -77, 12, -39, -41, -33, -31, -15, -9, -4, -56, -42, 80, 12, -4, 47, -34, -62, -36, 24, 6, 57, 28, 38, 9, 88, 15, 78, -17, 42, -9, 19, 34, 88, 58, 28, 53, -32, -22, 79, -7, 19, 61, 51, 4, 12, -9, 9, -37, 44, 60, 65, 44, 25, 73, -60, 7, 
  15, -27, -7, -26, 7, -4, -63, 27, 64, -14, 75, -38, -88, 73, -43, -51, -52, 19, 19, -61, 44, 50, -50, 26, -73, -71, -35, -69, 5, -43, 47, -84, -59, 25, -60, -71, -57, -35, 28, -62, -110, 35, -66, -8, -21, 34, -68, -40, -60, -61, -4, 34, 2, 2, -43, -41, 74, -14, 67, -14, 4, 44, -18, 54, 35, 71, 49, 68, 3, 25, 36, -24, 
  29, 17, -32, -33, -85, 29, 18, -11, 37, 46, -23, 41, -11, 16, 48, 73, -2, 45, 44, 29, -37, 75, -60, 49, 37, -1, -7, 0, -8, -16, 40, -21, -3, 56, -6, 36, 23, -56, 34, 78, 46, -17, 42, -34, 56, -14, -52, -5, -23, 48, 38, 15, 46, 65, 45, -31, 64, 47, -35, 66, 21, -28, 31, -8, 18, 47, 30, -31, 29, 62, -53, 76, 
  -40, -60, -50, -22, 34, -20, -41, -68, 12, -73, -81, -44, 9, 11, -42, 13, -65, -54, 12, -30, -75, -55, 13, -33, 13, -38, 6, 39, -65, 66, 9, -8, 62, -54, -25, -32, 2, -74, -14, -13, -31, 13, -10, 25, 17, -81, 49, -34, -39, -27, 31, -42, -12, -19, -37, -67, 20, -46, 14, -22, -81, 24, -27, -41, -67, 40, -49, -47, 25, 4, -76, 17, 
  34, 14, 88, 86, 40, 2, 22, 49, 40, 39, -27, 81, 15, 55, -21, 7, -33, 49, 81, -19, 73, -5, -34, 98, -13, -40, -5, 43, 3, -17, 17, -49, 15, 39, -4, 79, 82, -45, 52, -36, -65, -18, 83, -43, 14, -19, -29, 61, -20, 3, -28, -8, 27, 33, 50, -82, 42, -20, -45, -30, 60, -78, 39, 110, -45, 43, 49, -33, 29, 45, 9, -13, 
  -54, -10, 27, -62, 36, -7, -41, 5, -17, -23, -43, -38, -53, -35, -62, -31, 3, -56, -31, 19, -54, 54, -39, 29, -28, -55, -12, -18, -57, -49, 29, -32, -49, -59, 54, 42, 15, -52, -56, -24, -53, 5, -41, 25, -7, -14, 49, 5, -55, -78, -7, -58, 13, -47, 38, -55, -48, -44, -20, 42, -28, -31, -47, 39, 34, -40, 43, -47, -3, 42, 50, 33, 
  28, 57, 1, -7, 11, -29, 39, 16, 36, 61, -34, 38, 57, 9, -13, -15, 3, -56, -26, 21, -9, -54, 46, -21, 0, -9, -3, -21, 9, 92, -36, -11, 99, -30, -17, 68, -51, -4, 46, -2, -51, -9, 27, 18, 30, -36, -84, 45, 11, -17, 37, 44, -72, 40, 45, -46, 48, -35, -45, 68, -29, 45, -29, 47, -51, 17, 15, -44, -23, -12, -65, 63, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,72 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0039917556568980217, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.058468353003263474, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<1, float> quant8_scale = { 1, { 0.10205092281103134, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,6 } };
const TfArray<1, float> quant9_scale = { 1, { 0.26835453510284424, } };
const TfArray<1, int> quant9_zero = { 1, { 24 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension3, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1440, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_792000_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_792000_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
